abaseURL = "http://example.org/"
languageCode = "en-us"
title = "Ahiru"
theme = "cactus"
copyright = "none"

[params]
  projectsUrl = "https://github.com/mruwnik"
  css = ["/css/custom.css"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Media"
url = "https://media.ahiru.pl"
weight = 2

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

